from models import Sequence

data = [
    Sequence(
        id="3e3f55faf9eb104b05a96726ce040ea9",
        sequence="GTGCCAGCACCGCGGTAATACGAAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGCGTGCGTAGGTGGTTATTTAAGTCCGTTGTGAAAGCCCTGGGCTCAACCTGGGAACTGCAGTGGATACTGGATGACTAGAGTGTGGTAGAGGGTAGCGGAATTCCTGGTGTAGCAGTGAAATGCGTAGAGATCAGGAGGAACATCCATGGCGAAGGCAGCTACCTGGACCAACACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGG",
    ),
    Sequence(
        id="18cf07bed73dd66d28694d9cb55e2f69",
        sequence="TACGAAGGGGGCTAGCGTTGTTCGGAATCACTGGGCGTAAAGCGCGCGTAGGCGGACCGTTAAGTCGGAGGTGAAAGCCTGGAGCTCAACTCCAGAACTGCCTTCGATACTGGCGGTCTCGAGTCCGGGAGAGGTGAGTGGAACTGCTAGTGTAGAGGTGAAATTCGTAGATATTAGCAAGAACACCAGTGGCGAAGGCGGCTCACTGGCCCGGTACTGACGCTGAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGAAACCCGTGTAGT",
    ),
    Sequence(
        id="3c71894fed0b2e3370157b1dc22692d8",
        sequence="TACGAAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGCGTGCGTAGGTGGTGGTTTAAGTCCGTTGTGAAAGCCCTGGGCTCAACCTGGGAACTGCAGTGGATACTGGATCACTAGAGTGTGGCAGAGGGTAGTGGAATTCCCGGTGTAGCAGTGAAATGCGTAGAGATCGGGAGGAACATCAGTGGCGAAGGCGACTGCCTGGGCCAACACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCCTGTAGT",
    ),
    Sequence(
        id="27ca6df92022914cd8598a4df23d9ce3",
        sequence="TACGGAGGGAGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCACGTAGGCGGCTTTGTAAGTCAGAGGTGAAAGCCTGGAGCTCAACTCCAGAACTGCCTTTGAGACTGCATCGCTTGAATCCGGGAGAGGTGAGTGGAATTCCGAGTGTAGAGGTGAAATTCGTAGATATTCGGAAGAACACCAGTGGCGAAGGCGGCTCACTGGACCGGTATTGACGCTGAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGAAACCCGAGTAGT",
    ),
    Sequence(
        id="51e261fda7e94270e41dd93c7ce039cf",
        sequence="TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTTGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGAAACCCCAGTAGT",
    ),
    Sequence(
        id="c6f4a54e2fa6312c73af31d3513b7f3a",
        sequence="TACGTAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTTTGCTAAGACCGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTGGTGACTGGCAGGCTAGAGTATGGCAGAGGGGGGTAGAATTCCACGTGTAGCAGTGAAATGCGTAGAGATGTGGAGGAATACCGATGGCGAAGGCAGCCCCCTGGGCCAATACTGACGCTCATGCACGAAAGCGTGGGGAGCAAACAGGATTAGAAACCCCAGTAGT",
    ),
]
